spring:
  application:
    name: recrute-backend
  datasource:
    username: recrute_user
    password: recrute_pass
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/recrute?characterEncoding=UTF-8&useUnicode=true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true
file:
  upload-dir: uploads/cv
  upload-pdp-dir: uploads/pdp

jwt:
  secret: recruteSecretKey404E635266556A586E3272357538782F413F4428472B4B6250645367566B59
  expiration: 86400000

server:
  port: 8080