spring:
  application:
    name: recrute-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/recrute
    username: recrute_user
    password: recrute_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
  security:
    user:
      name: admin
      password: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: uploads/cv

server:
  port: 8080